services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: messaging
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d messaging"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      temporal:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      TEMPORAL_TARGET: temporal:7233
      TEMPORAL_NAMESPACE: default
      API_BASE_URL: http://api:8000
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/messaging
      WAREHOUSE_URL: postgresql://postgres:postgres@dw:5432/warehouse

  dw:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: warehouse
    ports:
      - "5440:5432"
    volumes:
      - pgdata_dw:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d warehouse"]
      interval: 5s
      timeout: 5s
      retries: 10

  temporal-postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: temporal
      POSTGRES_PASSWORD: temporal
      POSTGRES_DB: temporal
    volumes:
      - temporal_pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U temporal -d temporal"]
      interval: 5s
      timeout: 5s
      retries: 20

  temporal:
    image: temporalio/auto-setup:1.24
    depends_on:
      temporal-postgres:
        condition: service_healthy
    environment:
      DB: postgres12
      DB_PORT: 5432
      POSTGRES_USER: temporal
      POSTGRES_PWD: temporal
      POSTGRES_SEEDS: temporal-postgres
    ports:
      - "7233:7233"
    healthcheck:
      test: ["CMD", "tctl", "--address", "temporal:7233", "cluster", "health"]
      interval: 10s
      timeout: 10s
      retries: 10

  temporal-ui:
    image: temporalio/ui:latest
    environment:
      TEMPORAL_ADDRESS: temporal:7233
      TEMPORAL_CORS_ORIGINS: http://localhost:8000
    ports:
      - "8080:8080"
    depends_on:
      - temporal

  etl-worker:
    build: .
    # Fuerza a ejecutar el worker (no Uvicorn)
    entrypoint: ["python","-m","app.temporal.worker"]
    environment:
      TEMPORAL_TARGET: temporal:7233
      TEMPORAL_NAMESPACE: default
      API_BASE_URL: http://api:8000
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/messaging
      # Para psycopg2.connect en activities usamos 'postgresql://'
      WAREHOUSE_URL: postgresql://postgres:postgres@dw:5432/warehouse
    depends_on:
      db:
        condition: service_healthy
      dw:
        condition: service_healthy
      temporal:
        condition: service_healthy
      api:
        condition: service_started
    volumes:
      - .:/app
    restart: unless-stopped

  spark-master:
    image: apache/spark:3.5.1
    container_name: spark-master
    command: ["/opt/spark/bin/spark-class","org.apache.spark.deploy.master.Master","--host","spark-master"]
    ports:
      - "8081:8080"
      - "7077:7077"
    volumes:
      - ./spark/apps:/opt/spark-apps
      - ./spark/data:/opt/spark-data
    depends_on:
      dw:
        condition: service_healthy

  spark-worker:
    image: apache/spark:3.5.1
    container_name: spark-worker
    command: ["/opt/spark/bin/spark-class","org.apache.spark.deploy.worker.Worker","spark://spark-master:7077"]
    environment:
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
    volumes:
      - ./spark/apps:/opt/spark-apps
      - ./spark/data:/opt/spark-data
    depends_on:
      - spark-master

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: postgres
      MB_DB_HOST: metabase-db
    volumes:
      - metabase-data:/metabase-data
    depends_on:
      metabase-db:
        condition: service_healthy
      dw:
        condition: service_healthy

  metabase-db:
    image: postgres:16
    container_name: metabase-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: metabase
    volumes:
      - metabase-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d metabase"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  pgdata:
  pgdata_dw:
  temporal_pg:
  metabase-data:
  metabase-db-data: