server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Logs de la API
  - job_name: api
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        regex: 'api'
        action: keep
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs: attrs
      - json:
          expressions:
            tag: attrs.tag
            level: attrs.level
            message: attrs.message
          source: output
      - labels:
          level:
          service:
          container:
      - output:
          source: message

  # Logs de PostgreSQL
  - job_name: postgres
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        regex: '(db|dw|metabase-db|temporal-postgres)'
        action: keep
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
      - json:
          expressions:
            message: attrs.message
          source: output
      - labels:
          service:
          container:
      - output:
          source: message

  # Logs de Spark
  - job_name: spark
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        regex: '(spark-master|spark-worker)'
        action: keep
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
      - json:
          expressions:
            message: attrs.message
          source: output
      - labels:
          service:
          container:
      - output:
          source: message

  # Logs de Metabase
  - job_name: metabase
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        regex: 'metabase'
        action: keep
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
      - json:
          expressions:
            message: attrs.message
          source: output
      - labels:
          service:
          container:
      - output:
          source: message

  # Logs de Temporal
  - job_name: temporal
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        regex: '(temporal|etl-worker)'
        action: keep
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
      - json:
          expressions:
            message: attrs.message
          source: output
      - labels:
          service:
          container:
      - output:
          source: message

